### ISSUE TITLE
Acts of Kindness Cards

### ISSUE THREAD

**Issue by claudio-cruz** [HMuraja/happiness-unleashed#68]
As a **user** I want ** to see "Acts of Kindness" cards displayed prominently on the home page** so that **I can be inspired by uplifting stories and quotes, motivating me to engage in acts of kindness myself.**

### Acceptance Criteria:
- [ ] **Responsive:** 
- [ ] **Horizontal scroll:**  
- [ ] **Like Button:**
- [ ] **Check Button:** 
- [ ] **Change Button:** 
- [ ] **Random Cards:**

**Comment by HMuraja** [comment]
Duplicate
